openapi: 3.0.3
info:
  title: Book Store Api
  description: Book Store Api
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/'
security:
  - BearerAuth: []
paths:
  /api/register:
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        422:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /api/login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        422:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        401:
          description: Credentials does not match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicError'
  /api/logout:
    delete:
      summary: Logout
      responses:
        204:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicError'
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    UserRequest:
      type: object
      properties:
        email:
          type: string
          example: johndoe@mail.com
        name:
          type: string
          example: John Doe
        password:
          type: string
          example: 123ASd34
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: johndoe@mail.com
        name:
          type: string
          example: John Doe
        created_at:
          type: string
          format: date-time
          example: '2024-05-18T15:16:26.000000Z'
        updated:
          type: string
          format: date-time
          example: '2024-05-18T15:16:26.000000Z'
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: johndoe@mail.com
        password:
          type: string
          example: 123445321
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: tp30A8gRg0P7tKDvmLHqJmW6F44oOtaqTrAyAdJ5ab47f101
        expires_at:
          type: string
          format: date-time
          example: '2024-05-18T15:16:26.000000Z'
    ValidationError:
      type: object
      properties:
        message:
          type: string
          example: The email has already been taken.
        errors:
          type: object
          properties:
            email:
              type: array
              items:
                type: string
                example: The email has already been taken.
    BasicError:
      type: object
      properties:
        message:
          type: string
          example: Error message.





